### POST
POST http://localhost:8080/api/product
Content-Type: application/json

{
  "name" : "pen",
  "price": 6.3
}



### GET
GET http://localhost:8080/api/product/1
Accept: application/json



### GET
GET http://localhost:8080/api/product
Accept: application/json



### PUT
PUT http://localhost:8080/api/product/2
Content-Type: application/json

{
  "id" : 2,
  "name": "pen",
  "price": 1.99
}


### DELETE
DELETE http://localhost:8080/api/product/1
Accept: application/json
