spring:
  application:
    name: SecurityEx

  datasource:
    url: jdbc:mysql://localhost:3306/newdb
    username: root
    password: wjdwodud98
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  security:
    user:
      name: user
      password: 1234

server:
  port: 9999
jwt:
  secretKey: 12345678901234567890123456789012
  refreshKey: 12345678901234567890123456789012
